query GetAdminByUsername($username: String = "") {
  admin(where: {username: {_eq: $username}}) {
    id
    password
  }
}

query AdminGetMe($id: uuid!) {
  admin_by_pk(id: $id) {
    username
  }
}

mutation InsertAdmin($password: String!, $username: String!) {
  insert_admin_one(object: {password: $password, username: $username}) {
    id
  }
}
